wams/WaMS/Models/Band.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace WaMS.Models
{
    public class Band
    {
        public int BandID { get; set; }

        [Display(Name= "Band Name")]
        public string BandName { get; set; }
      
        public Person Fan { get; set; }

        [Display(Name = "Number of Fans")]
        public int fancounter { get; set; }


        public List<Person> Fans { get; set; }

        public Person PersonID { get; set; }
    }
}

wams/WaMS/Controllers/BandsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using WaMS.Models;

namespace WaMS.Controllers
{
    public class BandsController : Controller
    {
        private WaMSContext db = new WaMSContext();

        // GET: Bands
        public ActionResult Index()
        {
            updatefancounter();                                                         //ensures number of fans is up to date when the index is viewed
            return View(db.Bands.ToList());
        }

        // GET: Bands/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Band band = db.Bands.Find(id);
            if (band == null)
            {
                return HttpNotFound();
            }

            getfancounter(band, id);                                                    //updates number of fans for current band
            ViewFans(id);                                                               //retrieves list of fans for current band
            return View(band);
        }

        //displays one particular fan and their information
        public ActionResult DetailsPerson (int? id)
        {
            var PeopleController = DependencyResolver.Current.GetService<PeopleController>();
            var result = PeopleController.viewfans(id);
            Person hugefan = db.People.Find(id);
            return View(hugefan);
        }



        //calls getfancounter with every band in order to update all fan numbers
        public int updatefancounter ()
        {
            foreach( var item in db.Bands)
            {
                getfancounter(item, item.BandID);
            }
            return 0;
        }

        //updates the number of fands for the current band being sent in
        public Band getfancounter(Band band, int? id)
        {
            int fancount = 0;
            switch (band.BandName)
            {
                case "The Beatles":
                {
                    foreach(var item in db.People)
                        {                            
                            if (item.BandFan1 == true)
                            {
                                fancount++;
                            }
                        }
                    band.fancounter = fancount;
                        break;
                }
                case "The Rolling Stones":
                    {
                        foreach (var item in db.People)
                        {
                            if (item.BandFan2 == true)
                            {
                                fancount++;
                            }
                        }
                        band.fancounter = fancount;
                        break;
                    }
                case "Franz Ferdinand":
                    {
                        foreach (var item in db.People)
                        {
                            if (item.BandFan3 == true)
                            {
                                fancount++;
                            }
                        }
                        band.fancounter = fancount;
                        break;
                    }
                case "The Ramones":
                    {
                        foreach (var item in db.People)
                        {
                            if (item.BandFan4 == true)
                            {
                                fancount++;
                            }
                        }
                        band.fancounter = fancount;
                        break;
                    }
                case "Pink Floyd":
                    {
                        foreach (var item in db.People)
                        {
                            if (item.BandFan5 == true)
                            {
                                fancount++;
                            }
                        }
                        band.fancounter = fancount;
                        break;
                    }

                default:
                    break;
            }

            return band;
        }


        //updates and lists all fans for the current band id
        public ActionResult ViewFans(int? id)
        {
            Band band = db.Bands.Find(id);
            List<Person> fanlist = new List<Person>();


            switch (band.BandName)
            {
                case "The Beatles":
                    {
                        foreach (var item in db.People)
                        {
                            if (item.BandFan1 == true)
                            {
                                fanlist.Add(item);
                            }
                        }
                        break;
                    }
                case "The Rolling Stones":
                    {
                        foreach (var item in db.People)
                        {
                            if (item.BandFan2 == true)
                            {
                                fanlist.Add(item);
                            }
                        }
                        break;
                    }
                case "Franz Ferdinand":
                    {
                        foreach (var item in db.People)
                        {
                            if (item.BandFan3 == true)
                            {
                                fanlist.Add(item);
                            }
                        }
                        break;
                    }
                case "The Ramones":
                    {
                        foreach (var item in db.People)
                        {
                            if (item.BandFan4 == true)
                            {
                                fanlist.Add(item);
                            }
                        }
                        break;
                    }
                case "Pink Floyd":
                    {
                        foreach (var item in db.People)
                        {
                            if (item.BandFan5 == true)
                            {
                                fanlist.Add(item);
                            }
                        }
                        break;
                    }

                default:
                    break;
            }

            band.Fans = fanlist;
            db.SaveChanges();

            return RedirectToAction("Index");
        }

        /*
            Create, edit, and delete are not currently being used in this implementation of the project. They are being left in for future iterations 
             */

        // GET: Bands/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Bands/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "BandID,BandName")] Band band)
        {
            if (ModelState.IsValid)
            {
                db.Bands.Add(band);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(band);
        }

        // GET: Bands/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Band band = db.Bands.Find(id);
            if (band == null)
            {
                return HttpNotFound();
            }
            return View(band);
        }

        // POST: Bands/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "BandID,BandName")] Band band)
        {
            if (ModelState.IsValid)
            {
                db.Entry(band).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(band);
        }

        // GET: Bands/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Band band = db.Bands.Find(id);
            getfancounter(band, id);
            if (band == null)
            {
                return HttpNotFound();
            }
            return View(band);
        }

        // POST: Bands/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Band band = db.Bands.Find(id);
            db.Bands.Remove(band);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

wams/WaMS/Controllers/PeopleController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using WaMS.Models;

namespace WaMS.Controllers
{
    public class PeopleController : Controller
    {
        private WaMSContext db = new WaMSContext();

        // GET: People
        public ActionResult Index()
        {
            return View(db.People.ToList());
        }

        // GET: People/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Person person = db.People.Find(id);
            if (person == null)
            {
                return HttpNotFound();
            }
            return View(person);
        }
        public ActionResult viewfans(int? id)
        {
            return RedirectToAction("Index");
        }
        public ActionResult ExtendedIndex()
        {
            return View(db.People.ToList());
        }

        //initilizing test data, if data already exists does nothing
        public ActionResult Initialize()
        {
            int personCounter = 0;

            foreach (var item in db.People)
            {
               if (db.People.Find(item.PersonID) != null)
                {
                    personCounter++;
                }
            }
            if (personCounter == 0)
            {
                Person alex = new Person();                                     //creating new person and their attributes
                alex.FirstName = "Alex";
                alex.LastName = "Nguyen";
                alex.Email = "alenguye@gmail.com";
                alex.BandFan1 = true;
                alex.BandFan2 = true;
                alex.BandFan3 = true;
                alex.BandFan4 = true;
                alex.BandFan5 = true;

                Person Sydney = new Person();
                Sydney.FirstName = "Sydney";
                Sydney.LastName = "Skopos";
                Sydney.Email = "sskopos@gmail.com";
                Sydney.BandFan1 = true;
                Sydney.BandFan2 = true;
                Sydney.BandFan3 = false;
                Sydney.BandFan4 = false;
                Sydney.BandFan5 = true;

                Person Russell = new Person();
                Russell.FirstName = "Russell";
                Russell.LastName = "Wang";
                Russell.Email = "Russell@gmail.com";
                Russell.BandFan1 = false;
                Russell.BandFan2 = false;
                Russell.BandFan3 = false;
                Russell.BandFan4 = true;
                Russell.BandFan5 = true;

                db.People.Add(alex);                                            //saving people to database
                db.People.Add(Sydney);
                db.People.Add(Russell);
                db.SaveChanges();


            }
 
            return RedirectToAction("Index");

        }

        // GET: People/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: People/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "PersonID,FirstName,LastName,Email,BandFan1,BandFan2,BandFan3,BandFan4,BandFan5")] Person person)
        {
            if (ModelState.IsValid)
            {
                db.People.Add(person);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(person);
        }

        // GET: People/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Person person = db.People.Find(id);
            if (person == null)
            {
                return HttpNotFound();
            }
            return View(person);
        }

        // POST: People/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "PersonID,FirstName,LastName,Email,BandFan1,BandFan2,BandFan3,BandFan4,BandFan5")] Person person)
        {
            if (ModelState.IsValid)
            {
                db.Entry(person).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(person);
        }

        // GET: People/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Person person = db.People.Find(id);
            if (person == null)
            {
                return HttpNotFound();
            }
            return View(person);
        }

        // POST: People/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Person person = db.People.Find(id);
            db.People.Remove(person);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

wams/WaMS/Views/Bands/Create.cshtml
@model WaMS.Models.Band

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Band</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.BandName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.BandName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.BandName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

wams/WaMS/Views/Bands/Delete.cshtml
@model WaMS.Models.Band

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Band</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.BandName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.BandName)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.fancounter)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.fancounter)
        </dd>
    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

wams/WaMS/Views/Bands/Details.cshtml
@model WaMS.Models.Band

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>Band</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.BandName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.BandName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.fancounter)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.fancounter) fans
        </dd>
        <dt>

        <dt>
            Fan Names
        </dt>

        @foreach (var item in Model.Fans)
            {
            <dd>
               @Html.ActionLink(item.FirstName +" "+ item.LastName, "DetailsPerson", new { id = item.PersonID })
            </dd>
        }

    </dl>
</div>

<p>
    <!--  @Html.ActionLink("Edit", "Edit", new { id = Model.BandID }) |-->
    @Html.ActionLink("Back to List", "Index")
</p>

wams/WaMS/Views/Bands/DetailsPerson.cshtml
@model WaMS.Models.Person

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>Person</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.FirstName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.FirstName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.LastName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.LastName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Email)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Email)
        </dd>

        </br>
        <hr />
        <dd>
            Fan of Band
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.BandFan1)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.BandFan1)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.BandFan2)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.BandFan2)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.BandFan3)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.BandFan3)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.BandFan4)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.BandFan4)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.BandFan5)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.BandFan5)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Back to List of People", "Index", "People") | 
    @Html.ActionLink("Back to List of Bands", "Index")


</p>

wams/WaMS/Views/Bands/Edit.cshtml
@model WaMS.Models.Band

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Band</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.BandID)

        <div class="form-group">
            @Html.LabelFor(model => model.BandName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.BandName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.BandName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

wams/WaMS/Views/Bands/Index.cshtml
@model IEnumerable<WaMS.Models.Band>

@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>

<p>
    <!-- @Html.ActionLink("Create New", "Create") -->
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.BandName)
        </th>

        <th>
            @Html.DisplayNameFor(model => model.fancounter)
        </th>

        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.BandName)
        </td>

        <td>
            @Html.DisplayFor(modelItem => item.fancounter)
        </td>
        <td>
            <!--   @Html.ActionLink("Edit", "Edit", new { id=item.BandID }) |-->
            @Html.ActionLink("Band Details", "Details", new { id=item.BandID }) 
            <!-- | @Html.ActionLink("Delete", "Delete", new { id=item.BandID })-->
        </td>
    </tr>
}

</table>

wams/WaMS/Views/Bands/ViewFans.cshtml
@model IEnumerable<WaMS.Models.Person>

@{
    ViewBag.Title = "Index";
}

<h2>Fans</h2>

<p>
    @Html.ActionLink("Add New Person", "Create") |  @Html.ActionLink("Expanded View", "ExtendedIndex")
</p>

<table class="table">

    <tr>
        <th>
            @Html.DisplayNameFor(model => model.FirstName)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.LastName)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Email)
        </th>
        <th>
        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.FirstName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.LastName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Email)
            </td>

        </tr>
    }

</table>